# - name: Demo on loops
#   hosts: localhost
  connection: local
  tasks:
    - name: print fruit name
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      loop: 
        - apple
        - orange
        - grapes
        - banana

    - name: print fruit name with quantity
      ansible.builtin.debug:
        msg: fruit name - {{ item.name }}, quantity - {{ item.quantty }}
      loop: 
        - { name: apple, quantity: 100 }
        - { name: orange, quantity: 200 }
        - { name: grapes, qtuantity: 300 }
        - { name: banana, quantity: 400 }

- name: Loops
  hosts: localhost
  connection: local
  tasks:
    - name: print skills
      ansible.builtin.debug:
        msg: skill name - {{ item }}
      loop:
        - DevOps
        - Linux
        - Monitoring
        - IaC